package com.wuyuan.webapps.pojo;

public class Authority {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column authority.id
     *
     * @mbggenerated Fri Mar 02 17:20:22 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column authority.resource
     *
     * @mbggenerated Fri Mar 02 17:20:22 CST 2018
     */
    private String resource;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column authority.name
     *
     * @mbggenerated Fri Mar 02 17:20:22 CST 2018
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column authority.id
     *
     * @return the value of authority.id
     *
     * @mbggenerated Fri Mar 02 17:20:22 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column authority.id
     *
     * @param id the value for authority.id
     *
     * @mbggenerated Fri Mar 02 17:20:22 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column authority.resource
     *
     * @return the value of authority.resource
     *
     * @mbggenerated Fri Mar 02 17:20:22 CST 2018
     */
    public String getResource() {
        return resource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column authority.resource
     *
     * @param resource the value for authority.resource
     *
     * @mbggenerated Fri Mar 02 17:20:22 CST 2018
     */
    public void setResource(String resource) {
        this.resource = resource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column authority.name
     *
     * @return the value of authority.name
     *
     * @mbggenerated Fri Mar 02 17:20:22 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column authority.name
     *
     * @param name the value for authority.name
     *
     * @mbggenerated Fri Mar 02 17:20:22 CST 2018
     */
    public void setName(String name) {
        this.name = name;
    }
}