package com.wuyuan.webapps.pojo;

import java.util.Date;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.id
     *
     * @mbggenerated Fri Jan 26 10:14:39 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_name
     *
     * @mbggenerated Fri Jan 26 10:14:39 CST 2018
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.password
     *
     * @mbggenerated Fri Jan 26 10:14:39 CST 2018
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.gender
     *
     * @mbggenerated Fri Jan 26 10:14:39 CST 2018
     */
    private String gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.address
     *
     * @mbggenerated Fri Jan 26 10:14:39 CST 2018
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.birthplace
     *
     * @mbggenerated Fri Jan 26 10:14:39 CST 2018
     */
    private String birthplace;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.birthday
     *
     * @mbggenerated Fri Jan 26 10:14:39 CST 2018
     */
    private Date birthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.education
     *
     * @mbggenerated Fri Jan 26 10:14:39 CST 2018
     */
    private String education;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.industry
     *
     * @mbggenerated Fri Jan 26 10:14:39 CST 2018
     */
    private String industry;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.position
     *
     * @mbggenerated Fri Jan 26 10:14:39 CST 2018
     */
    private String position;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.income
     *
     * @mbggenerated Fri Jan 26 10:14:39 CST 2018
     */
    private String income;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.online
     *
     * @mbggenerated Fri Jan 26 10:14:39 CST 2018
     */
    private String online;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.recent_online
     *
     * @mbggenerated Fri Jan 26 10:14:39 CST 2018
     */
    private Date recentOnline;
    private String recentOnline2;

    public String getRecentOnline2() {
		return recentOnline2;
	}

	public void setRecentOnline2(String recentOnline2) {
		this.recentOnline2 = recentOnline2;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.create_time
     *
     * @mbggenerated Fri Jan 26 10:14:39 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.declaration
     *
     * @mbggenerated Fri Jan 26 10:14:39 CST 2018
     */
    private String declaration;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.id
     *
     * @return the value of user.id
     *
     * @mbggenerated Fri Jan 26 10:14:39 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.id
     *
     * @param id the value for user.id
     *
     * @mbggenerated Fri Jan 26 10:14:39 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_name
     *
     * @return the value of user.user_name
     *
     * @mbggenerated Fri Jan 26 10:14:39 CST 2018
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_name
     *
     * @param userName the value for user.user_name
     *
     * @mbggenerated Fri Jan 26 10:14:39 CST 2018
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.password
     *
     * @return the value of user.password
     *
     * @mbggenerated Fri Jan 26 10:14:39 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.password
     *
     * @param password the value for user.password
     *
     * @mbggenerated Fri Jan 26 10:14:39 CST 2018
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.gender
     *
     * @return the value of user.gender
     *
     * @mbggenerated Fri Jan 26 10:14:39 CST 2018
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.gender
     *
     * @param gender the value for user.gender
     *
     * @mbggenerated Fri Jan 26 10:14:39 CST 2018
     */
    public void setGender(String gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.address
     *
     * @return the value of user.address
     *
     * @mbggenerated Fri Jan 26 10:14:39 CST 2018
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.address
     *
     * @param address the value for user.address
     *
     * @mbggenerated Fri Jan 26 10:14:39 CST 2018
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.birthplace
     *
     * @return the value of user.birthplace
     *
     * @mbggenerated Fri Jan 26 10:14:39 CST 2018
     */
    public String getBirthplace() {
        return birthplace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.birthplace
     *
     * @param birthplace the value for user.birthplace
     *
     * @mbggenerated Fri Jan 26 10:14:39 CST 2018
     */
    public void setBirthplace(String birthplace) {
        this.birthplace = birthplace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.birthday
     *
     * @return the value of user.birthday
     *
     * @mbggenerated Fri Jan 26 10:14:39 CST 2018
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.birthday
     *
     * @param birthday the value for user.birthday
     *
     * @mbggenerated Fri Jan 26 10:14:39 CST 2018
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.education
     *
     * @return the value of user.education
     *
     * @mbggenerated Fri Jan 26 10:14:39 CST 2018
     */
    public String getEducation() {
        return education;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.education
     *
     * @param education the value for user.education
     *
     * @mbggenerated Fri Jan 26 10:14:39 CST 2018
     */
    public void setEducation(String education) {
        this.education = education;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.industry
     *
     * @return the value of user.industry
     *
     * @mbggenerated Fri Jan 26 10:14:39 CST 2018
     */
    public String getIndustry() {
        return industry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.industry
     *
     * @param industry the value for user.industry
     *
     * @mbggenerated Fri Jan 26 10:14:39 CST 2018
     */
    public void setIndustry(String industry) {
        this.industry = industry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.position
     *
     * @return the value of user.position
     *
     * @mbggenerated Fri Jan 26 10:14:39 CST 2018
     */
    public String getPosition() {
        return position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.position
     *
     * @param position the value for user.position
     *
     * @mbggenerated Fri Jan 26 10:14:39 CST 2018
     */
    public void setPosition(String position) {
        this.position = position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.income
     *
     * @return the value of user.income
     *
     * @mbggenerated Fri Jan 26 10:14:39 CST 2018
     */
    public String getIncome() {
        return income;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.income
     *
     * @param income the value for user.income
     *
     * @mbggenerated Fri Jan 26 10:14:39 CST 2018
     */
    public void setIncome(String income) {
        this.income = income;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.online
     *
     * @return the value of user.online
     *
     * @mbggenerated Fri Jan 26 10:14:39 CST 2018
     */
    public String getOnline() {
        return online;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.online
     *
     * @param online the value for user.online
     *
     * @mbggenerated Fri Jan 26 10:14:39 CST 2018
     */
    public void setOnline(String online) {
        this.online = online;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.recent_online
     *
     * @return the value of user.recent_online
     *
     * @mbggenerated Fri Jan 26 10:14:39 CST 2018
     */
    public Date getRecentOnline() {
        return recentOnline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.recent_online
     *
     * @param recentOnline the value for user.recent_online
     *
     * @mbggenerated Fri Jan 26 10:14:39 CST 2018
     */
    public void setRecentOnline(Date recentOnline) {
        this.recentOnline = recentOnline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.create_time
     *
     * @return the value of user.create_time
     *
     * @mbggenerated Fri Jan 26 10:14:39 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.create_time
     *
     * @param createTime the value for user.create_time
     *
     * @mbggenerated Fri Jan 26 10:14:39 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.declaration
     *
     * @return the value of user.declaration
     *
     * @mbggenerated Fri Jan 26 10:14:39 CST 2018
     */
    public String getDeclaration() {
        return declaration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.declaration
     *
     * @param declaration the value for user.declaration
     *
     * @mbggenerated Fri Jan 26 10:14:39 CST 2018
     */
    public void setDeclaration(String declaration) {
        this.declaration = declaration;
    }
}