package com.wuyuan.webapps.pojo;

public class UserRelAuthority {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_rel_authority.id
     *
     * @mbggenerated Fri Mar 02 17:20:22 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_rel_authority.user_id
     *
     * @mbggenerated Fri Mar 02 17:20:22 CST 2018
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_rel_authority.authority_id
     *
     * @mbggenerated Fri Mar 02 17:20:22 CST 2018
     */
    private Integer authorityId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_rel_authority.id
     *
     * @return the value of user_rel_authority.id
     *
     * @mbggenerated Fri Mar 02 17:20:22 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_rel_authority.id
     *
     * @param id the value for user_rel_authority.id
     *
     * @mbggenerated Fri Mar 02 17:20:22 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_rel_authority.user_id
     *
     * @return the value of user_rel_authority.user_id
     *
     * @mbggenerated Fri Mar 02 17:20:22 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_rel_authority.user_id
     *
     * @param userId the value for user_rel_authority.user_id
     *
     * @mbggenerated Fri Mar 02 17:20:22 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_rel_authority.authority_id
     *
     * @return the value of user_rel_authority.authority_id
     *
     * @mbggenerated Fri Mar 02 17:20:22 CST 2018
     */
    public Integer getAuthorityId() {
        return authorityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_rel_authority.authority_id
     *
     * @param authorityId the value for user_rel_authority.authority_id
     *
     * @mbggenerated Fri Mar 02 17:20:22 CST 2018
     */
    public void setAuthorityId(Integer authorityId) {
        this.authorityId = authorityId;
    }
}